all: gen/figures/session_duration.png \
     gen/figures/videos_viewed.png \
     gen/figures/sessions_per_user.png \
     gen/figures/daily_sessions.png

gen/figures/session_duration.png \
gen/figures/videos_viewed.png \
gen/figures/sessions_per_user.png \
gen/figures/daily_sessions.png:
	Rscript src/session-analysis/analysis.R